### ISSUE TITLE
missing loading class definition for notification with status loading

### ISSUE THREAD

**Issue by amit034** [LouisBarranqueiro/reapop-theme-bootstrap#1]
when creating notification with status loading.. the element is not rendered with loading icon

**Comment by LouisBarranqueiro** [comment]
**EDITED**

Hey @amit034, there is no loading status for this theme. Would you like to have one like the WYBO theme?

**Comment by amit034** [comment]
+1

**Comment by LouisBarranqueiro** [comment]
added on [v0.3.0](https://github.com/LouisBarranqueiro/reapop-theme-bootstrap/releases/tag/v0.3.0). also update Reapop version to have smooth collapsing feature
