### ISSUE TITLE
Theme missing className in proptypes

### ISSUE THREAD

**Issue by barriber** [LouisBarranqueiro/reapop-theme-bootstrap#2]
Hi,

I receive the following warning when using theme with reapop.

Required prop `theme.notificationsSystem.className` was not specified in `NotificationsSystem`. Check the render method of `Connect(NotificationsSystem)`.

**Comment by LouisBarranqueiro** [comment]
Hey @barriber,

i'm on it :)

**Comment by jsardev** [comment]
I'm experiencing the same issue. Do you need any help with the fix? :)

**Comment by jsardev** [comment]
@LouisBarranqueiro Could you please take a look at the PR? :)

**Comment by LouisBarranqueiro** [comment]
`NotificationSystem.classNames` is now optional - just update reapop module - https://github.com/LouisBarranqueiro/reapop/releases/tag/v0.6.1

**Comment by barriber** [comment]
Thanks!

**Comment by jsardev** [comment]
Thank You! :)

**Comment by LouisBarranqueiro** [comment]
Sorry for the waiting, i'm so busy :D
