### ISSUE TITLE
Possible to change the License?

### ISSUE THREAD

**Issue by DonBras** [LouisBarranqueiro/reapop-theme-bootstrap#6]
![gpl3](https://user-images.githubusercontent.com/13163148/36798191-3213628e-1caa-11e8-945e-f4695b911fc7.jpg)

Is there a special reason why you choose GPL-3 over MIT, like reapop actually has?

**Comment by LouisBarranqueiro** [comment]
👋 @DonBras, nice image 😄 I forgot to change it. I'll do it today.

**Comment by DonBras** [comment]
Nice one👍 and thx for the quick response!

**Comment by LouisBarranqueiro** [comment]
License updated 🎉 😄

**Comment by DonBras** [comment]
Horrayyy 😃🙌🎉
